version: '3.1'

services:
  api:
    image: suwhan2/nativenavs:latest
    container_name: nativenavs-8081
    environment:
      - TZ=Asia/Seoul
      - LANG=ko_KR.UTF-8
      - HTTP_PORT=8081
    ports:
      - '8081:8080'
