springdoc:
  swagger-ui:
    path: /swagger
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: alpha




spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ssafyd110@gmail.com
    password: qzvzxehofrkhhfat
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true



cloud:
  aws:
    s3:
      bucket: nativenavs
    credentials:
      access-key: AKIAQIJRRZNAE34YDWXX
      secret-key: ENC(NKtINeQJYRu8mUVC4JGRlMaU+VNhBhUfFruvMeRLCFqniy7euTBpiMyioaW660udQSuQSQGOMtU=)
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    key: 110110



